"""
LogForge Alert & Incident Models
"""

from sqlalchemy import Column, Integer, String, DateTime, Float, Text, Boolean, ForeignKey, JSON
from sqlalchemy.sql import func
from app.core.database import Base


class Alert(Base):
    """Security/operational alert generated by the platform."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(300), nullable=False)
    description = Column(Text)
    severity = Column(String(20), index=True)  # LOW, MEDIUM, HIGH, CRITICAL
    alert_type = Column(String(100), index=True)  # brute_force, anomaly, cpu_spike, etc.

    # Source info
    source = Column(String(100))
    ip_address = Column(String(50))
    username = Column(String(100))

    # Timing
    triggered_at = Column(DateTime, server_default=func.now(), index=True)
    resolved_at = Column(DateTime)
    is_resolved = Column(Boolean, default=False, index=True)
    acknowledged_by = Column(String(100))

    # AI Analysis
    ai_analysis = Column(Text)         # Root cause analysis from AI
    remediation = Column(Text)         # Suggested remediation steps
    related_log_ids = Column(JSON, default=[])

    # Scoring
    confidence_score = Column(Float, default=0.0)  # 0-1
    event_count = Column(Integer, default=1)

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "alert_type": self.alert_type,
            "source": self.source,
            "ip_address": self.ip_address,
            "username": self.username,
            "triggered_at": self.triggered_at.isoformat() if self.triggered_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "is_resolved": self.is_resolved,
            "acknowledged_by": self.acknowledged_by,
            "ai_analysis": self.ai_analysis,
            "remediation": self.remediation,
            "confidence_score": self.confidence_score,
            "event_count": self.event_count,
            "related_log_ids": self.related_log_ids or [],
        }


class Incident(Base):
    """High-level security incident grouping multiple alerts."""

    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(300), nullable=False)
    description = Column(Text)
    severity = Column(String(20))
    status = Column(String(50), default="open")  # open, investigating, resolved, false_positive

    started_at = Column(DateTime, server_default=func.now())
    resolved_at = Column(DateTime)

    # AI-generated content
    root_cause = Column(Text)
    impact_summary = Column(Text)
    remediation_steps = Column(JSON, default=[])
    timeline = Column(JSON, default=[])

    alert_ids = Column(JSON, default=[])
    affected_systems = Column(JSON, default=[])

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "status": self.status,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "root_cause": self.root_cause,
            "impact_summary": self.impact_summary,
            "remediation_steps": self.remediation_steps or [],
            "timeline": self.timeline or [],
            "alert_ids": self.alert_ids or [],
            "affected_systems": self.affected_systems or [],
        }
